### ISSUE TITLE
Error while running plugin in KiCAD 8

### ISSUE THREAD

**Issue by zisi** [nikisalli/Kicad-nikfemm#1]
Hey!! I'm trying to run the plugin but i get this error:

``` python
Traceback (most recent call last):
  File "/home/azisi/.local/share/kicad/8.0/3rdparty/plugins/com_github_nikisalli_nikfemm/__init__.py", line 869, in Run
    ItemList = Get_PCB_Elements(board, connect)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azisi/.local/share/kicad/8.0/3rdparty/plugins/com_github_nikisalli_nikfemm/__init__.py", line 225, in Get_PCB_Elements
    temp["FootprintReference"] = Pad.GetParent().GetReference()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BOARD_ITEM_CONTAINER' object has no attribute 'GetReference'
```

**Comment by usbalbin** [comment]
How about something like this?

```patch
--- a/plugins/__init__.py
+++ b/plugins/__init__.py
@@ -221,8 +221,8 @@ def Get_PCB_Elements(board: pcbnew.BOARD, connect: pcbnew.CONNECTIVITY_DATA):
             temp["Area"] = ToMM(ToMM(Pad.GetEffectivePolygon().Area()))
             temp["PadName"] = Pad.GetPadName()
             
-            if Pad.GetParent():
-                temp["FootprintReference"] = Pad.GetParent().GetReference()
+            if Pad.GetParentFootprint():
+                temp["FootprintReference"] = Pad.GetParentFootprint().GetReference()
 
         elif type(Pad) is pcbnew.ZONE:
             # pcbnew.ZONE().GetZoneName
```

**Comment by zisi** [comment]
Thanks!! It works!!

But i got this error:

```python
Traceback (most recent call last):
  File "/home/azisi/.local/share/kicad/8.0/3rdparty/plugins/com_github_nikisalli_nikfemm/__init__.py", line 740, in OnStartSimulation
    merged_shapes, drills = Get_Outlines(self.data, choosen_net=choosen_net)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azisi/.local/share/kicad/8.0/3rdparty/plugins/com_github_nikisalli_nikfemm/__init__.py", line 469, in Get_Outlines
    shapes[l][-1] = shapely.affinity.scale(shapes[l][-1], d["Size"][0] / 2, d["Size"][1] / 2)
                    ^^^^^^^^^^^^^^^^
AttributeError: module 'shapely' has no attribute 'affinity'
```

But i think it is related to my set-up. Thanks again. The issue is resolved.

**Comment by nikisalli** [comment]
> How about something like this?
> 
> ```diff
> --- a/plugins/__init__.py
> +++ b/plugins/__init__.py
> @@ -221,8 +221,8 @@ def Get_PCB_Elements(board: pcbnew.BOARD, connect: pcbnew.CONNECTIVITY_DATA):
>              temp["Area"] = ToMM(ToMM(Pad.GetEffectivePolygon().Area()))
>              temp["PadName"] = Pad.GetPadName()
>              
> -            if Pad.GetParent():
> -                temp["FootprintReference"] = Pad.GetParent().GetReference()
> +            if Pad.GetParentFootprint():
> +                temp["FootprintReference"] = Pad.GetParentFootprint().GetReference()
>  
>          elif type(Pad) is pcbnew.ZONE:
>              # pcbnew.ZONE().GetZoneName
> ```

just merged this after testing it
I'm currently not developing this plugin as it is more some kind of demo to see if the simulator is any good to be included natively into kicad (see discussion here https://gitlab.com/kicad/code/kicad/-/issues/8398#note_1777623893)

thank you very much for the quick fix!
