### ISSUE TITLE
BOARD_ITEM_CONTAINER object has no attribute 'GetReference'

### ISSUE THREAD

**Issue by gymprince** [nikisalli/Kicad-nikfemm#3]
### Steps to repeat

- When I click the icon 'FEM', error dialog (shown as attached) pop up and cannot continue. 
![Workspace 1_001](https://github.com/nikisalli/Kicad-nikfemm/assets/23411219/f69cb048-3b1a-45ca-b62f-9782ba37b807)

- I tried several PCB files, same error occurred.
- My KiCad version is shown as follows:
```
Application: KiCad x86_64 on x86_64

Version: 8.0.1-8.0.1-0~ubuntu20.04.1, release build

Libraries:
	wxWidgets 3.2.1
	FreeType 2.10.1
	HarfBuzz 2.6.4
	FontConfig 2.13.1
	libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

Platform: Ubuntu 20.04.6 LTS, 64 bit, Little endian, wxGTK, X11, ubuntu, x11

Build Info:
	Date: Mar 14 2024 15:11:44
	wxWidgets: 3.2.1 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.71.0
	OCC: 7.6.3
	Curl: 7.68.0
	ngspice: 42
	Compiler: GCC 9.4.0 with C++ ABI 1013

Build settings:

```

**Comment by nikisalli** [comment]
Hello, it should work now, I forgot to push the updated zip package.
Let me know if further problems persist

**Comment by nikisalli** [comment]
Hi, did the update work?
I'm closing the issue as the problem should be fixed with the latest commit
feel free to reopen the issue if further problems arise
